version: "2"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /volume1/docker/sonarr:/config
      - /volume1/media/tv:/tv
      - /volume1/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
