version: '2'
services:
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - PUID=<PUID>
      - PGID=<PGID>
      - VERSION=latest
    network_mode: host
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/docker/plex/transcode:/transcode
      - /volume1/media/tv/:/media/tv
      - /volume1/media/movies:/media/movies
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
