version: "2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/New_York
      - RUN_OPTS=
    volumes:
      - /volume1/docker/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
